config/routes.rb
CricketApp::Application.routes.draw do
  resources :grounds
  resources :players
  resources :teams do
    resources :players
    resources :grounds
  end
  resources :users do
    resources :teams
  end
  resources :sessions,    only: [:new, :create, :destroy]
  resources :microposts,  only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost = current_user.microposts.build if signed_in?
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Cricket</h1>
<p>
  This is all about Cricket stuff.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Cricket</h1>
<p>
  Contact us about Cricket stuff.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Cricket Help</h1>
<p>
  Help with how to do Cricket stuff.
</p>

app/views/static_pages/home.html.erb
<div class="home-page-body">
  <div class="center hero-unit">
    <h1 class="home-h1">CRICKET</h1>

    <h2 style="color: white">
    	Basic cricket simulation stuff!
    </h2>

<% if !signed_in? %>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>   <%= link_to "Sign in!", signin_path, class: "btn btn-large" %>
<% end %>
  </div>
</div>