config/routes.rb
CricketApp::Application.routes.draw do
  resources :grounds
  resources :players
  resources :teams do
    resources :players
    resources :grounds
  end
  resources :users do
    resources :teams
  end
  resources :sessions,    only: [:new, :create, :destroy]
  resources :microposts,  only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/ground.rb
# == Schema Information
#
# Table name: grounds
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  address    :text
#  country_id :integer
#  capacity   :integer
#  url        :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Ground < ActiveRecord::Base
  belongs_to :country
  has_many :teams

  validates :name, presence: true

end

app/controllers/grounds_controller.rb
class GroundsController < ApplicationController

  def index
    @grounds = Ground.all
  end

  def show
    @ground = Ground.find(params[:id])
  end

  def new
    if admin?
      @ground = Ground.new
    else
      flash[:notice] = "Tsk tsk tsk, you can't go creating grounds just yet."
      redirect_to root_path
    end
  end

  def create
    if admin?
      @ground = Ground.new(ground_params)
      if @ground.save
        flash[:success] = "#{@ground.name} created successfully!"
        redirect_to @ground
      else
        render 'new'
      end
    else
      redirect_to root_path
    end
  end

  def edit
    if admin?
      @ground = Ground.find(params[:id])
    else
      flash[:notice] = "Tsk tsk tsk, you can't go editing grounds just yet."
      redirect_to players_path
    end
  end

  def update
    @ground = Ground.find(params[:id])
    if @ground.update_attributes(ground_params)
      flash[:success] = "All done - #{@ground.name} updated."
      redirect_to @ground
    else
      render 'edit'
    end
  end

  private

    def ground_params
      params.require(:ground).permit(:name, :address, :country_id, :capacity, :url)
    end

end

app/helpers/grounds_helper.rb
module GroundsHelper
end

app/views/grounds/edit.html.erb
<% provide(:title, 'Edit ground') %>
<h1>Edit Ground</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@ground) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :address %>
      <%= f.text_area :address %>

      <%= f.label :country_id %>
      <%= f.collection_select :country_id, Country.all, :id, :name %>

      <%= f.label :capacity %>
      <%= f.text_field :capacity %>

      <%= f.label :url %>
      <%= f.text_field :url %>
      <br>
      <%= f.submit "Update ground", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/grounds/index.html.erb
<% provide(:title, 'Grounds') %>
<h1>Grounds</h1>


  <% if admin? %>
<div class="btn-group">
    <%= link_to "Add new ground", new_ground_path, class: "btn" %>
</div>
  <% end %>
 
<div class="row">
  <div class="span4">
  <% @grounds.each do |ground| %>
    <ul>
      <li><%= link_to "#{ground.name}", ground %></li>
    </ul>
  <% end %>
  </div>
</div>

app/views/grounds/new.html.erb
<% provide(:title, 'Add ground') %>
<h1>Add Ground</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@ground) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :address %>
      <%= f.text_area :address %>

      <%= f.label :country_id %>
      <%= f.collection_select :country_id, Country.all, :id, :name %>

      <%= f.label :capacity %>
      <%= f.text_field :capacity %>

      <%= f.label :url %>
      <%= f.text_field :url %>
      <br>
      <%= f.submit "Create ground", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/grounds/show.html.erb
<% provide(:title, @ground.name) %>
<h1><%= @ground.name %></h1>
<% if signed_in? && admin? %>
<%= link_to "Edit", edit_ground_path(@ground) %>
<% end %>

<dl class="dl-horizontal">
  <dt>Address</dt>
    <dd><%= @ground.address %></dd>
  <dt>Country</dt>
    <dd><%= @ground.country.name %></dd>
  <dt>Capacity</dt>
    <dd><%= @ground.capacity %></dd>
  <dt>Website</dt>
    <dd><%= @ground.url %></dd>
</dl>