config/routes.rb
CricketApp::Application.routes.draw do
  resources :grounds
  resources :players
  resources :teams do
    resources :players
    resources :grounds
  end
  resources :users do
    resources :teams
  end
  resources :sessions,    only: [:new, :create, :destroy]
  resources :microposts,  only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <strong><%= link_to "Cricket", root_path %></strong> by Ben Wickerson
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_game_menu.html.erb
<li id="fat-menu" class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Game <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%=link_to "Teams", teams_path %></li>
    <li><%=link_to "Players", players_path %></li>
    <li><%=link_to "Grounds", grounds_path %></li>
  </ul>
</li>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Cricket", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to '<i class="icon-home"></i>'.html_safe, root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <%= render 'layouts/game_menu' %>
          <% if signed_in? %>
            <%= render 'layouts/user_menu' %>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_user_menu.html.erb
<li id="fat-menu" class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= @current_user.name %> <b class="caret"></b>
  </a>

  <ul class="dropdown-menu">
    <% if signed_in? %>
    <li class="nav-header">My Stuff</li>
    <li><%=link_to "My Teams", user_teams_url(@current_user.id) %></li>
    <li><%=link_to "New Team", new_team_path %></li>
    <% end %>
    <% if admin? %>
    <li class="divider"></li>
    <li class="nav-header">Admin</li>
    <li><%=link_to "New Player", new_player_path %></li>
    <li><%=link_to "New Ground", new_ground_path %></li>
    <% end %>
        <li class="divider"></li>
    <li><%= link_to "Profile", current_user %></li>
    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
    <li><%= link_to "Users", users_path %></li>
    <li class="divider"></li>
    <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", 
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>